### PR TITLE
Countrypicker test

### LINKED ISSUE #148: Integrating with nicklockwood/CountryPicker
Wanted a flag based country name functionality integrated in ActionsheetPicket. I use the code of Country picker and integrate same as two spearate files on Actionsheetpciker + the resources used

### PR DESCRIPTION
**Pull request by vkumarsharma**
Integrated the country selection. The flags not showing currently because i don’t have knowledge as how to use bundles from a library.
This fix #148.

### CODE REVIEW

**Comment by skywinder** [comment]
Thanks! Still don't see the flags after merge. When this bug will be fixed - I will be glad to merge it!

**Comment by vkumarsharma** [comment]
Have to include the country picker bundle in build phase of action picker. Now the flags show.

**Comment by vkumarsharma** [comment]
It now shows the flags correctly. I have checked in the changes

**Comment by vkumarsharma** [comment]
merged the latest changes in branch. Now the flags show. 


     On Thursday, May 7, 2015 5:15 PM, Petr Korolev <notifications@github.com> wrote:
   

 Thanks! Still don't see the flags after merge. When this bug will be fixed - I will be glad to merge it!—

**Pull request closed without merging**
