### PR TITLE
Reduced minimum iOS version back to 9.0

### LINKED ISSUE #522: Minimum iOS version
In your last commits, did you mean to bump the minimum iOS version to 12?

The lowest Xcode 12 will allow is iOS 9, however it's auto updater sets it to 12.0 which means when building with Carthage it is not building the armv7 slice.

Can I/you change it back to 9.0 minimum?

### PR DESCRIPTION
**Pull request by ddaddy**
Closes #522

### CODE REVIEW

**Comment by ddaddy** [comment]
Not sure why Travis gave the error `An error occurred while generating the build script.`

**Comment by ddaddy** [comment]
Never mind, I found a way to make it re-test with an empty commit.

**Review by skywinder — APPROVED** [review]

**Comment by ddaddy** [comment]
Any chance we can get a new release pushed with this change?

**Comment by noorulain17** [comment]
@skywinder do you want to publish a new release or I'll do this ?

**Pull request merged**
