### PR TITLE
update deprecated classes: UIPopoverPresentationController

### PR DESCRIPTION
**Pull request by cutmail**
This PR does 3 things:

* Apply recommended settings for Xcode 12.
* Change minimum deployment target from iOS 8.0 to iOS 9.0 since Xcode 12 dropped support for iOS 8.0.
* Replace UIPopoverController with UIPopoverPresentationController to fix deprecated warnings.

### CODE REVIEW

**Review by noorulain17 — DISMISSED** [review]

**Comment by noorulain17** [comment]
@cutmail Thank you for this PR.
I checked out your branch, there are some warnings in `CoreActionSheetPicker` code that needs to be catered before dropping support for iOS 9.0.
Please update your PR after fixing those warnings.
Screenshot 2020-09-20 at 2 26 48 AM

**Comment by skywinder** [comment]
thanks for update, @cutmail 
agree with @noorulain17:
To complete this PR, please make changes in example projects to remove warnings and make whole project consistent so we can merge your PR!

**Review by skywinder — CHANGES_REQUESTED** [review]
please fix warnings in example project

**Comment by skywinder** [comment]
@cutmail is there any  updates?

**Comment by cutmail** [comment]
@skywinder Sorry for late, I'm fixing warnings!

**Comment by skywinder** [comment]
thanks for update, @cutmail 👍 

@noorulain17 please, have a look. looks legit.

**Comment by noorulain17** [comment]
Thanks @cutmail. Looks good.

@skywinder I'll test this tonight.

**Comment by noorulain17** [comment]
@cutmail / @skywinder tested. Looks fine.
I think we're good to merge. Just need to rebase it with latest `develop` branch

**Review by noorulain17 — APPROVED** [review]

**Review by skywinder — APPROVED** [review]

**Comment by noorulain17** [comment]
@cutmail please rebase your branch with `skywinder:develop`

**Comment by cutmail** [comment]
@noorulain17 Sorry for late, I rebased branch. Please check.

**Comment by skywinder** [comment]
Yes, looks very nice, thank you!

**Pull request merged**
