### PR TITLE
Fixes #205 Add blur feature for picker background

### LINKED ISSUE #205: Blur instead of semi transparent black overlay
I don't see that option, is it available? If not, that could be great.

### PR DESCRIPTION
**Pull request by nikola-mladenovic**
Added `pickerBlurRadius` property for setting the desired blur radius for picker background blur effect.

It works only if `pickerBackgroundColor` is nil and the device is iPhone (iPad isn't currently supported due to issue with grabbing the snapshot image from UIPopoverController frame).

@skywinder - if you agree I'd like to add an example to `ActionSheetPickerTableViewController` so it can be tried out easily?

### CODE REVIEW

**Comment by skywinder** [comment]
@nikola-mladenovic Yes, add please example to test and demonstrate it! Thank you! :+1:

**Comment by nikola-mladenovic** [comment]
@skywinder - thanks, added one more static cell in `ActionSheetPickerTableViewController` which opens a picker with blur radius set to `picker.pickerBlurRadius = @(10)`

Please note that there's a storyboard change for this static cell, just in case you have some work going on on that particular storyboard on some other branch.

**Comment by nikola-mladenovic** [comment]
@skywinder - have you had a chance to look at this one? Any feedback perhaps? ☺️

**Comment by skywinder** [comment]
@nikola-mladenovic sorry for delay! Looks good! Can you also add a couple string in readme about this feature?

**Comment by nikola-mladenovic** [comment]
No worries - yes, will add them and update the PR 😊

**Comment by tbaranes** [comment]
For your information, in #205 I was thinking about a blur instead of the black transparent overlay, not in the picker. So, it shouldn't close this issue, but still, that a nice feature you have here!

**Comment by skywinder** [comment]
@nikola-mladenovic Thank you for the PR! 👍  
Already in `2.1.0` 🎉

**Comment by nikola-mladenovic** [comment]
Great news @skywinder - and yes, I'm going to try and add desc to readme by the end of this week! 😊

**Comment by nikola-mladenovic** [comment]
@tbaranes - I didn't get that from the desc in the issue; how about you create a new one for the that feature, and we'll create a new PR for that one?

**Comment by tbaranes** [comment]
Sounds good @nikola-mladenovic, do you mind to take care of this?

**Comment by masonk** [comment]
I can't build the example projects with the latest version of ASP 3.0 

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CIContext", referenced from:
      objc-class-ref in AbstractActionSheetPicker.o
  "_OBJC_CLASS_$_CIFilter", referenced from:
      objc-class-ref in AbstractActionSheetPicker.o
  "_OBJC_CLASS_$_CIImage", referenced from:
      objc-class-ref in AbstractActionSheetPicker.o
  "_kCIInputImageKey", referenced from:
      -[AbstractActionSheetPicker blurPickerBackground] in AbstractActionSheetPicker.o
  "_kCIInputRadiusKey", referenced from:
      -[AbstractActionSheetPicker blurPickerBackground] in AbstractActionSheetPicker.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Which could be related to this commit.

**Comment by skywinder** [comment]
@masonk I don't see any issues yet.
that's could be a problem with some archs setups. try to clean your build.

**Comment by masonk** [comment]
It's not that.  I think it's related to the deployment target.

When I build your example projects, only the ActionSheetPicker-iOS-5-7 project produces this linker error, the others don't.

**Pull request merged**
