### PR TITLE
Fix run ActionSheetPickerTests on Xcode and Travis CI

### PR DESCRIPTION
**Pull request by nowsprinting**
- Remove shared scheme `ActionSheetPickerTests` (need only on build target)
- Remove TestTableViewController.m from build target `ActionSheetPickerTests`'s membership
- Fix .travis.yml
    - Remove commented-out lines
    - Fix specified scheme name
    - Add `osx_image`
    - Add `-destination` option on `xcodebuild` command
- Fix tests
    - Fix duplicate global field (`UIView`)`origin`

### CODE REVIEW

**Comment by saad352** [comment]
Any idea when this pull request will be merged? 
The main developers doesn't seem to be active.

**Comment by nowsprinting** [comment]
@saad352 This repository owner looks active to me.
I think that it will be merged someday, so I will wait. (and pray...)

**Comment by skywinder** [comment]
@nowsprinting yay! thank a lot. I'm very appreciated for that fix! 
Sorry for a long answer. I'm fully on other project and sometimes miss the PR's here.

**Comment by nowsprinting** [comment]
@skywinder Thanks!

**Pull request merged**
