### PR TITLE
Fixes presentation issue on iPads

### LINKED ISSUE #187: ActionSheetPickerView  Picker View not appearing for iPAD
The picker view is inflating with iPhone and not in iPad how to fix this issue.
Thanks in advance

### PR DESCRIPTION
**Pull request by maciekish**
THis PR will Close #187

### CODE REVIEW

**Comment by skywinder** [comment]
Hi! Thank for contribution. Can you explain, in which cases I can occur this presentation issue? (better with screenshots before/after)

**Comment by maciekish** [comment]
Hi, if i run this code on an iPad with iOS 8.x the picker doesn't appear at all. The screen is dimmed and the invisible picker is cancelled if i tap anywhere: http://s.swic.name/ZZe5

The view passed in is a `UILabel` in a `UITableViewCell`, but the same issue manifests if i use `self.view` as origin instead. Same issue in objc in another app as well so its not Swift related.

After my fix the picker appears nicely from the label in the cell.

**Comment by alexwald** [comment]
please review, I'm facing the same issue.

**Comment by skywinder** [comment]
@alexwald, @maciekish  It's weird, I can't reproduce this bug in my examples.
I'll be very grateful if you could show me how to reproduce this bug

Is it necessary to use `CGRectMake(_containerView.frame.size.width / 2.f, 0.f, 0, 0)`? Why not just `_containerView.bounds`? can you check - is it works correctly in that case?
Then we can simplify code by remove on of the redundant if-statement.

**Comment by skywinder** [comment]
@alexwald can you provide screenshot, how it's look like?

**Comment by skywinder** [comment]
@maciekish can you provide details about your pull request? In which  cases it can be useful?

**Comment by skywinder** [comment]
@maciekish  with this fix Picker stops presenting from `UIbarbuttonitem`

**Comment by mbijapur** [comment]
What's the solution for this issue?

**Comment by skywinder** [comment]
@mbijapur it is the solution. do you have any issue for now?

**Pull request merged**
