### PR TITLE
Compiler Warning fixed

### PR DESCRIPTION
**Pull request by StefaniOSApps**
fixed compiler warning (UiBarButtonItem is not KindOfClass UiView)

### CODE REVIEW

**Comment by StefaniOSApps** [comment]
only ActionSheetDatePicker

**Comment by skywinder** [comment]
@StefaniOSApps I tried to build your versions - by analyzing via Xcode - looks it doesn't consider as warrnings.
Looks like origin should be always kind of `UIView.` Isn't it?
Can you explain, why did you made this changes?

**Comment by StefaniOSApps** [comment]
The pull request is a year old, so I can not answer a question about it. I only program with Swift.

**Comment by skywinder** [comment]
@StefaniOSApps got it. I will close it, since looks like it does not generate warrning now.

 thanks for contributions anyway.

**Pull request closed without merging**
