### PR TITLE
[Fix] import issue on Swift Pacakge

### PR DESCRIPTION
**Pull request by Wei18**
as title

### CODE REVIEW

**Comment by ddaddy** [comment]
Can we please get this PR merged?
The only way to use this package with SPM is to directly reference this commit hash.

**Comment by danilobias** [comment]
It would be nice if this PR could be merged, I'm having the same issues with SPM as well

**Comment by APvanGrootel** [comment]
I have the same problem. I imported the develop branch, since master still gives the "module not found" error. And after that, I get 'CoreActionSheetPicker/AbstractActionSheetPicker.h' file not found. It would be very nice if this solution was merged, so we can use it.

**Comment by ddaddy** [comment]
I assume @skywinder doesn't get notifications from here :(

**Comment by mcat345** [comment]
why don't you just approve this PR? this is very needed fix

**Comment by Wei18** [comment]
How about me as a contributor, @skywinder.

**Comment by skywinder** [comment]
@Wei18 Missed you comment. here you go! 🚀
I appreciate your willingness to help with the project.

**Comment by Wei18** [comment]
I'll update a patch version for swift package (this PR).

**Pull request merged**
