### PR TITLE
Update source patterns

### PR DESCRIPTION
**Pull request by ElfSundae**
as discussed https://github.com/skywinder/ActionSheetPicker-3.0/pull/455#issuecomment-568773844

### CODE REVIEW

**Comment by skywinder** [comment]
Nice catch. even `pod lib lint`.
With installations and pushing of the pod, there is also doesn't show any issues.
thanks for cleaning up the podfile.

p.s. are you familiar with pushing podfiles to cocoapods repo?

**Comment by ElfSundae** [comment]
Yes, I maintain dozens of pods.

**Comment by skywinder** [comment]
@ElfSundae thanks. Please consider #348 , in case of your futer support of thins project, I would love to add you as contributor 👍

**Comment by ElfSundae** [comment]
@skywinder Thank you for thinking of me, I am sorry I can’t keep following this project for now, actually I haven't used this library for years, I just maintain the legacy projects now.

**Comment by skywinder** [comment]
Got it! Thanks :)

> @skywinder Thank you for thinking of me, I am sorry I can’t keep following this project for now, actually I haven't used this library for years, I just maintain the legacy projects now.

**Pull request merged**
