### PR TITLE
Fix Memory Leak & Fix import

### LINKED ISSUE #571: Error in v2.7.3 compilation issue
We are using ActionSheetPicker-3.0 (2.7.3) here we are getting below mentioned issue, this was not there in v2.7.1.

ActionSheetPicker-3 0 (2 7 3)_Issue

### PR DESCRIPTION
**Pull request by mlch911**
Fix import using CocoaPods.
Fix dismiss function not called in iPad.
Fix Memory Leak.

### CODE REVIEW

**Comment by skywinder** [comment]
Thanks for the update, @mlch911!

I am no longer supporting this library, as I am now 100% focused on blockchain R&D and audits at my company, where I dedicate all my time [www.oxor.io](http://www.oxor.io).

I appreciate your willingness to help with the project. I can add you to the list of contributors, so you can keep it alive if you're willing to continue its development.

P.S.
Here is an update about adding collaborators. Ping me if you're willing to keep it going.
[https://github.com/skywinder/ActionSheetPicker-3.0/issues/348](https://github.com/skywinder/ActionSheetPicker-3.0/issues/348)

**Comment by Wei18** [comment]
Hi @mlch911,
Please fix conflicts, thanks.

**Comment by mlch911** [comment]
> Thanks for the update, @mlch911!
> 
> I am no longer supporting this library, as I am now 100% focused on blockchain R&D and audits at my company, where I dedicate all my time [www.oxor.io](http://www.oxor.io).
> 
> I appreciate your willingness to help with the project. I can add you to the list of contributors, so you can keep it alive if you're willing to continue its development.
> 
> P.S. Here is an update about adding collaborators. Ping me if you're willing to keep it going. #348


Would be nice to help. Sorry for the late reply.

**Comment by mlch911** [comment]
> Hi @mlch911, Please fix conflicts, thanks.

@Wei18 Done.

**Comment by Wei18** [comment]
We still need fix warns (about import) after this PR merged.
- https://github.com/skywinder/ActionSheetPicker-3.0/issues/571#issuecomment-2002028175

**Comment by mlch911** [comment]
> We still need fix warns (about import) after this PR merged.
> - https://github.com/skywinder/ActionSheetPicker-3.0/issues/571#issuecomment-2002028175

I have modified the import method. Do I need to change it again?

**Comment by wei18** [comment]
> > We still need fix warns (about import) after this PR merged.
> > 
> > * [Error in v2.7.3 compilation issue #571 (comment)](https://github.com/skywinder/ActionSheetPicker-3.0/issues/571#issuecomment-2002028175)
> 
> I have modified the import method. Do I need to change it again?

It's ok. 
Some users who partially use Cocoapods encountered errors. Your recent changes have turned these errors into warnings, so we can address these warnings later.

**Comment by mlch911** [comment]
> > > We still need fix warns (about import) after this PR merged.
> > > 
> > > * [Error in v2.7.3 compilation issue #571 (comment)](https://github.com/skywinder/ActionSheetPicker-3.0/issues/571#issuecomment-2002028175)
> > 
> > 
> > I have modified the import method. Do I need to change it again?
> 
> It's ok. Some users who partially use Cocoapods encountered errors. Your recent changes have turned these errors into warnings, so we can address these warnings later.

I encountered these errors too. So I changed it.

**Comment by wei18** [comment]
> > > > We still need fix warns (about import) after this PR merged.
> > > > 
> > > > * [Error in v2.7.3 compilation issue #571 (comment)](https://github.com/skywinder/ActionSheetPicker-3.0/issues/571#issuecomment-2002028175)
> > > 
> > > 
> > > I have modified the import method. Do I need to change it again?
> > 
> > 
> > It's ok. Some users who partially use Cocoapods encountered errors. Your recent changes have turned these errors into warnings, so we can address these warnings later.
> 
> I encountered these errors too. So I changed it.

Could you provide workspace_example.zip and information about (xcode version, coaoapod version), let me reproduce this issue. I wanna update [CI_build.yml ](https://github.com/skywinder/ActionSheetPicker-3.0/blob/develop/.github/workflows/CIBuild.yml#L35).

**Comment by mlch911** [comment]
> > > > > We still need fix warns (about import) after this PR merged.
> > > > > 
> > > > > * [Error in v2.7.3 compilation issue #571 (comment)](https://github.com/skywinder/ActionSheetPicker-3.0/issues/571#issuecomment-2002028175)
> > > > 
> > > > 
> > > > I have modified the import method. Do I need to change it again?
> > > 
> > > 
> > > It's ok. Some users who partially use Cocoapods encountered errors. Your recent changes have turned these errors into warnings, so we can address these warnings later.
> > 
> > 
> > I encountered these errors too. So I changed it.
> 
> Could you provide workspace_example.zip and information about (xcode version, coaoapod version), let me reproduce this issue. I wanna update [CI_build.yml ](https://github.com/skywinder/ActionSheetPicker-3.0/blob/develop/.github/workflows/CIBuild.yml#L35).

Xcode 15.2, Cocoapods 1.11.3, haven't run `pod install`.
I Just use the Demo Project `ActionSheetPicker-3.0.xcworkspace`. At this commit `6a913a7ca489a8565afcf85c62a5a9d055934711` and build.
image

**Comment by wei18** [comment]
> > > > > > We still need fix warns (about import) after this PR merged.
> > > > > > 
> > > > > > * [Error in v2.7.3 compilation issue #571 (comment)](https://github.com/skywinder/ActionSheetPicker-3.0/issues/571#issuecomment-2002028175)
> > > > > 
> > > > > 
> > > > > I have modified the import method. Do I need to change it again?
> > > > 
> > > > 
> > > > It's ok. Some users who partially use Cocoapods encountered errors. Your recent changes have turned these errors into warnings, so we can address these warnings later.
> > > 
> > > 
> > > I encountered these errors too. So I changed it.
> > 
> > 
> > Could you provide workspace_example.zip and information about (xcode version, coaoapod version), let me reproduce this issue. I wanna update [CI_build.yml ](https://github.com/skywinder/ActionSheetPicker-3.0/blob/develop/.github/workflows/CIBuild.yml#L35).
> 
> Xcode 15.2, Cocoapods 1.11.3, haven't run `pod install`. I Just use the Demo Project `ActionSheetPicker-3.0.xcworkspace`. At this commit `6a913a7ca489a8565afcf85c62a5a9d055934711` and build. image

- Add #577

**Pull request merged**
