### PR TITLE
Added Xcode 11.x compatibility & DarkMode support

### PR DESCRIPTION
**Pull request by noorulain17**
- Added Xcode 11.x compatibility by adding AppIcon & LaunchScreen.storyboard
Screenshot 2020-04-28 at 2 12 14 PM

Screenshot 2020-04-28 at 1 24 45 PM

- Added DarkMode support for iOS 13.x
actionsheet

### CODE REVIEW

**Comment by skywinder** [comment]
Hello! thank you very much. Can you kindly check that cause merge conflicts in this branch?

**Comment by noorulain17** [comment]
> Hello! thank you very much. Can you kindly check that cause merge conflicts in this branch?

Sure, checking now.
Thanks for your positive response :)

**Comment by skywinder** [comment]
💎Brilliant!💎
 Thank you!

**Comment by skywinder** [comment]
@noorulain17 thanks for fixes of #473. It would be better to split it into 2 PR's. but let it go.  Much apreciated for the help with project!

**Comment by mikemike396** [comment]
Awesome! 🚀

**Pull request merged**
