### PR TITLE
Feature swift 4.2 migration

### PR DESCRIPTION
**Pull request by oklimberg**
I updated the project to the current recommended settings of Xcode 10.1, fixed some warnings and converted the Swift Sample project to Swift 4.2.

If there needs more to be done for Swift 4.2 migration, please lt me know.

### CODE REVIEW

**Comment by skywinder** [comment]
Thanks, @oklimberg . Is it automatic migration by Xcode? Did you add extra feature from your side?

**Comment by oklimberg** [comment]
Hi, and sorry for the late reply.
I did not add any new feature and only applied changes suggested by Xcode.

**Comment by skywinder** [comment]
Hello, @oklimberg .
Thank you for effort. I just updated the project, sadly it gets' a lot of conflicts for now.

I tried to merge your PR, but get a lot of errors, and finally, when I build a project it starts to throw errors. So I have to close this PR in favor of the newer version. But thank you very much for update. my fault, that I didn't update it in timing manner before.
I will do my best to  support it in future.

**Comment by skywinder** [comment]
I updated many files in recent update #447. please feel free to check, If I need to update something. I see your changes in code. 
 I'm out of ios dev now. So your suggestions are more than welcome

**Pull request closed without merging**
